# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b64846f4c43ab88b5639618462ad8aebcd38cb0270a88b43f72552d48ebafa8ac88a1e2ded628af037d24304593c550eeb231002258de579e0b99f03631288d1

test:
  secret_key_base: 170d648dad70ca9c959f4b6c0a7582144e4e81347255fd68bf104364635b35e5d14443145565871b79cfbae2dd334fb458bf3e067f116aaa8bc7c249c0fd9fbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
